project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Excercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
            
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
            
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
            
      - text: "In Class Exercise Excercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
            
          - text: "In-Class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
            
          - text: "In-Class Exercise 3 NKDE"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03_NKDE.html"
        
      - text: "Take home Exercise"
        menu:
          - text: "Take home Exercise 1"
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

